/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package procesos;

/**
 *
 * @author Sergio
 */
public class Ejercicio5 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTerminacionEstandar = new javax.swing.JButton();
        jButtonTerminacionConErrores = new javax.swing.JButton();
        jButtonNotepadRuntime = new javax.swing.JButton();
        jButtonDirPBuilder = new javax.swing.JButton();
        jButtonCambiaDirSalida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTerminacionEstandar.setText("Terminacion Estandar");
        jButtonTerminacionEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminacionEstandarActionPerformed(evt);
            }
        });

        jButtonTerminacionConErrores.setText("Terminacion con errores");
        jButtonTerminacionConErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerminacionConErroresActionPerformed(evt);
            }
        });

        jButtonNotepadRuntime.setText("Notepad Runtime");

        jButtonDirPBuilder.setText("Dir PBuilder");

        jButtonCambiaDirSalida.setText("CambiaDirSalida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTerminacionEstandar)
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonTerminacionConErrores)
                    .addComponent(jButtonNotepadRuntime)
                    .addComponent(jButtonDirPBuilder)
                    .addComponent(jButtonCambiaDirSalida))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonTerminacionEstandar)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jButtonTerminacionConErrores)
                .addGap(22, 22, 22)
                .addComponent(jButtonNotepadRuntime)
                .addGap(24, 24, 24)
                .addComponent(jButtonDirPBuilder)
                .addGap(23, 23, 23)
                .addComponent(jButtonCambiaDirSalida)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTerminacionConErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminacionConErroresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTerminacionConErroresActionPerformed

    private void jButtonTerminacionEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerminacionEstandarActionPerformed
        
    }//GEN-LAST:event_jButtonTerminacionEstandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCambiaDirSalida;
    private javax.swing.JButton jButtonDirPBuilder;
    private javax.swing.JButton jButtonNotepadRuntime;
    private javax.swing.JButton jButtonTerminacionConErrores;
    private javax.swing.JButton jButtonTerminacionEstandar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
